version: '3'

services:
  cart:
    build: './Angel_Service_Cart'
    ports:
      - "9000:8080"
  product:
    build: './Angel_Service_Product'
    ports:
      - "9001:8080"
  users:
    build: './Angel_Service_User'
    ports:
      - "9002:8080"
  order:
    build: './Angel_Service_OrderManagement'
    ports:
      - "9003:8080"